export enum ErrorCode {
  FAILED = 'FAILED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INVALID_SYNTAX = 'INVALID_SYNTAX',
  MALFORMED_COMMAND = 'MALFORMED_COMMAND',
  MALFORMED_EVENT = 'MALFORMED_EVENT',
  INVALID_ACTION = 'INVALID_ACTION',
  INVALID_TARGET = 'INVALID_TARGET',

  PRECONDITION_FAILED = 'PRECONDITION_FAILED',

  INVARIANT_VIOLATION = 'INVARIANT_VIOLATION',
  INVALID_RECIPIENT = 'INVALID_RECIPIENT',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_SESSION = 'INVALID_SESSION',
  INSUFFICIENT_AP = 'INSUFFICIENT_AP',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',

  // Domain-specific errors. Entities not found in `world` projection.
  ACTOR_NOT_FOUND = 'ACTOR_NOT_FOUND',
  SHELL_NOT_FOUND = 'SHELL_NOT_FOUND',
  PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  ITEM_NOT_FOUND_IN_ACTOR_INVENTORY = 'ITEM_NOT_FOUND_IN_ACTOR_INVENTORY',
}
