export enum ErrorCode {
  INVALID_SYNTAX = 'INVALID_SYNTAX',
  INVALID_ACTION = 'INVALID_ACTION',
  INVALID_TARGET = 'INVALID_TARGET',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  INVALID_RECIPIENT = 'INVALID_RECIPIENT',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_SESSION = 'INVALID_SESSION',
  INSUFFICIENT_AP = 'INSUFFICIENT_AP',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
}
