#!/usr/bin/env bash

# Find all .ts files in ./src directory and its subdirectories
find ./src -type f -name "*.ts" | sort | while read -r file; do
    # Extract the basename
    basename=$(basename "$file")
    
    # Print the file path and basename as a header
    
    echo -e "\n//--- $file ($basename) ---\n"
    
    # Print the file contents
    cat "$file"
done
